### ISSUE TITLE
Enable 'Select All' in 'Select Images' view on iOS

### ISSUE THREAD

**Issue by MagnusBrzenk** [Piwigo/Piwigo-Mobile#310]
**Is your feature request related to a problem? Please describe.**

I have 1000+ images in an album from my iOS photos and I want to upload them but there doesn't seem to be a 'Select All' option. As far as I can tell, I'd have to manually scroll through and press hundreds of individual 'select' buttons

**Describe the solution you'd like**
A button to 'Select All' right at the top of the 'Select Images' view (or in the hamburger-dropdown). If there is a way to select all already, then it is so hidden/non-intuitive that I would suggest implementing a simple 'Select All' button where I have just suggested.

**Describe alternatives you've considered**
Scrolling through and manually clicking on hundreds of 'select' buttons (like an idiot)

**Additional context**

**Comment by EddyLB** [comment]
Hi @MagnusBrzenk ,

Because of the existence of a memory leak (#267), we cannot (today) allow users to upload a large number of photos (say more than 70). We work on this issue but it looks to be a bug deep into the library we use.

To quickly select your photos, instead of tapping photos individually, I invite you to slide your finger to the left and then down, right, down, left, etc. continuously. This will be much much faster.

**Comment by EddyLB** [comment]
Memory leak fixed.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by EddyLB** [comment]
This option will come with the new management of uploads which will check the battery level.
