### ISSUE TITLE
Display "Your favorites" photos

### ISSUE THREAD

**Issue by EddyLB** [Piwigo/Piwigo-Mobile#319]
Display the user's favorite photos and videos as on the web interface.
Possible when https://github.com/Piwigo/Piwigo/pull/582 and https://github.com/Piwigo/Piwigo/pull/810 will be closed.

**Comment by plegall** [comment]
@abrenoch I'm making some changes on your code (indentation, function rename...) and I understand that you have never checked the "fetch another user's favorite photos" because you automatically get a fatal error. Considering you've made the code far more complex just to be able to get another user favorites, I'm confused. Even if I include the appropriate function file to have `get_username` function, the code doesn't work (I get some photos that are not accessible to the user...)

In my opinion, we should remove the user_id input parameter on pwg.users.getFavorites and simply use `check_user_favorites` and `get_sql_condition_FandF` mature functions. Later maybe, when needed we can add the user_id parameter. Allright?

**Comment by plegall** [comment]
The exact question is : for now, for Piwigo 2.10, do you really need to be able to fetch favorites of any user or getting the current user favorites would be enough?
