### ISSUE TITLE
Reduce video frame size before uploading

### ISSUE THREAD

**Issue by EddyLB** [Piwigo/Piwigo-Mobile#438]
The app proposes to resize photos before uploading. 
Why not videos?

**Comment by AD-Wright** [comment]
Why was this closed?  Is implementing video resizing too different from image resizing?  Was it implemented, and just combined with image resizing?

**Comment by AD-Wright** [comment]
So on more examination, it looks like this was implemented, and tied to the photo resize in the settings.  Would it be possible to separate out the video and picture resize / compression settings?  Pictures at the max image size for the device will take up much less space than the shortest video at the same size.  Reducing the max image size to shrink down video filesizes will shrink images too, even though the space savings is comparably much less.  
Or am I totally misreading the code?

**Comment by EddyLB** [comment]
Yes, this is implemented by adopting the frame sizes proposed by iOS. But I did not have the time to split the settings at that time. For photos, I thought I should replace the resize option in % to a resize option in pixels and keep the compression as it is. As for movies, I wanted to only present the available frame sizes (there is no compression option available). What are your thoughts?

**Comment by AD-Wright** [comment]
I see.  So minimum resolution on iOS is 640x480, and no compression available.  The percent -> fixed sizes makes perfect sense.  iPhone minimum video size with the Camera app is 720p, so 720p -> 480p should equate to a space savings of 60-70%.   Doing some testing, this appears to be happening correctly with the minimum photo size (5%) set.  So the app works great how it is right now.

Splitting video size and picture size may benefit those who are using Piwigo as a general photo backup - I'm moving to Piwigo from Google Photos due to the change in storage in June, and was starting to realize how much space the normal iPhone videos take up.  It also would make sense with video filesizes generally being larger - you may want 480p videos, but not 640x480 pictures!  

I have no idea how difficult this would be to implement, looking through the repository for "photoResize" shows a lot of places, is it as simple as creating a "videoResize" variable and putting it in a few files?  I have never programmed in Swift before.  Don't feel too pressured, I can work around by uploading videos and photos in separate batches, and changing the setting in between.  This feels like a useful feature though.
