### ISSUE TITLE
[Bug] Laggy scrolling of thumbnails and pauses during swiping through images

### ISSUE THREAD

**Issue by WhatIsThisAllAboutSilly** [Piwigo/Piwigo-Mobile#476]
**Describe the bug and how to reproduce**
Scrolling through thumbnails results in stuttering and lag as well as loosing the pre-cached thumbnails. (So the generic image pops up).

There is also stutter when moving through images in full screen view - although less noticeable.

**Steps to reproduce the behavior**
Scroll through albums with reasonable (at least 100 images).

**Expected behavior**
Smooth scrolling through all images (ideally with promotion on 120hz devices) without them popping into view.

(Native photos app deals with 30k+ images smoothly)

**What did you do already**
 - Search whether a similar issue is already reported? Doesn’t appear to be!
 - Check for known workarounds in the issue tracker? None found?
 - Did you check with guest login? N/A
 - Did you try to reproduce it with https://www.piwigo.org/demo/ ? No.

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro Max, iPad Pro 11” 1st Gen
 - OS: iOS 15
 - App version: 2.7.2

**Comment by WhatIsThisAllAboutSilly** [comment]
What version was this supposed to be fixed for?

Running 2.9.5, still lags scrolling through albums with both iPhone 13PM / iPad Pro.

**Comment by EddyLB** [comment]
Scrolling through albums should be smooth unless your server or Internet connexion is slow. When the images are in cache, the scrolling should be smooth.

Before the version 2.9, the iOS app was adding batches of images to the cache during the scroll, each batch corresponding to slightly more than the number of images necessary to fill the screen of the device. Since version 2.9, the cache is pre-filled with the total number of (known or unknown) images and loads missing ones in the background.

In a future version, we shall populate the cache when the app is in the background while the device is charging so that in most cases image data will be in cache before the user accesses the album. This will require a hige modification of the app.
