### ISSUE TITLE
Cannot connect to server

### ISSUE THREAD

**Issue by githubsharezone** [Piwigo/Piwigo-Mobile#481]
i installed piwigo on truneas but when i introduce username, pwd, etc.. on screen setup i recevie a error "Cannot connect to server" on log ngninx i see 

021/11/04 10:47:16 [error] 24072#100265: *40 FastCGI sent in stderr: "PHP message: PHP Warning:  mysqli::__construct(): (HY000/2002): No such file or directory in /usr/local/www/Piwigo/include/dblayer/functions_mysqli.inc.php on line 52PHP message: PHP Warning:  mysqli::set_charset(): Couldn't fetch mysqli in /usr/local/www/Piwigo/include/dblayer/functions_mysqli.inc.php on line 88" while reading response header from upstream, client: 172.25.10.11, server: piwigo.example.com, request: "POST /install.php?language=en_UK HTTP/1.1", upstream: "fastcgi://unix:/var/run/piwigo.example.com-php-fpm.sock:", host: "172.25.30.102", referrer: "http://172.25.30.102/install.php?language=en_UK"

if i try the connect on localhost mysql the user and pwd function.
I suppose that the erroe see on configuration but not undestand where

thank for support

**Comment by EddyLB** [comment]
Hi @githubsharezone 
The server returns an error after calling the [PHP method](https://www.php.net/manual/en/mysqli.set-charset.php) `set_charset()`. The Piwigo server app cannot connect to your database. Please post a message on the [forum](https://piwigo.org/forum/) to get some help.

I close this issue because it is not related with the iOS app.
