### ISSUE TITLE
Cycle through uploads instead of stopping 

### ISSUE THREAD

**Issue by mybuntu-git2** [Piwigo/Piwigo-Mobile#525]
Due to unrelated issues, the server sometimes fails to generate a thumbnail and the whole upload fails.
On one hand I propose to workaround all this  and send the posters/thumbnails directly from iOS, as this seems more reliable than waiting for a set of remote processes to complete.
But the main issue is, if 5-6 uploads fails, all the others will remain stuck. I suggest to cycle through all uploads at least once and not stopping at the sixth.

**Comment by EddyLB** [comment]
It is not recommended to cycle through all uploads because this may use a huge amount of disk space on the device and create issues. An alternative could be to fix a limit in disk space usage (knowing that the app cannot know how much space is available).
Please note that the app tries to resume failed uploads when the user launches it or in the background if the 'Background App Refresh" option is enabled in settings (triggered by iOS or a shortcut created by the user).

**Comment by mybuntu-git2** [comment]
hi,
I understand, the problem is that the app first tries to resume failed uploads.
my point is the app should try to resume all pending uploads and then the failed uploads at the end.
this would allow to complete an upload cycle, for example if say I have 100 photos I upload 5 then another 5 fail, upload stops. next time the sort order of the uploads should put the failed ones at the bottom.
this also allows to "postpone" the upload of files that fail because of latency issues. 
maybe also another optimisation could be to try to upload first the smallest files when not on wifi, basically trying to "get as much as possible done with low latency".
so something like, sort by size, adding a size penalty of "very big number" to previously failed uploads when sorting.

**Comment by EddyLB** [comment]
An upload encountering a network issue is resumable but an issue encountered while preparing the file to be uploaded is not resumable (rare case). So the app sorts issues with the aim to resume those which are resumable. May be, sometimes, the app does not "sort" issues properly or does not resume uploads as it should. Please report here which blocking errors were reported so that we can look into the issue.

**Comment by mybuntu-git2** [comment]
Hi, closing as I fixed manually the queue by using another upload tool so cannot reproduce. However I really suggest to put previously failed uploads at the bottom of the upload queue. It should automatically cover all scenarios as it is simply based on returncodes, and can coexist with other queuing strategies for further speedup.
