### ISSUE TITLE
Unable to view photos, app only shows default image 

### ISSUE THREAD

**Issue by borgeslm** [Piwigo/Piwigo-Mobile#95]
Using iOS 9.0 and Piwigo 2.0.1 (11) on iPhone 6+. Did a fresh install, connected to server and was able to create a album without any problems. The Album shows correctly the number of photos and the date created. The problem is that the app only shows the default image (mountain image), the uploaded photos are only viewable on the browser. Panoramic images are not viewable on the app and on the browser. Am I missing something? or is this app not updated to be compatible with iOS 9.0? Any help will be greatly appreciated.

On another note, I just want to reiterate my support for the outstanding work done on this program. Great Job!
![photo-2015-09-18-10-28-40_0834](https://cloud.githubusercontent.com/assets/14351025/9966425/b262fbc2-5df1-11e5-93d4-d5a965758a7b.PNG)
![photo-2015-09-18-10-28-35_0833](https://cloud.githubusercontent.com/assets/14351025/9966426/b2a872ec-5df1-11e5-945a-93064d4fce77.PNG)

**Comment by SpencerBaker** [comment]
That's definitely weird. It's working on my phone running iOS 9.0 and everything should work with iOS 9.

I assume you weren't having this problem before?

What happens if you pull to refresh, does the image stay as the default image? It only displays the mountain image if Piwigo doesn't give a URL for a thumbnail image or if the image fails to download.

Thanks for your support, thought you should know I've moved off of Piwigo since I've found another app that does the exact same thing (Google Photos).

**Comment by borgeslm** [comment]
This is an initial install, wasn't running Piwigo before. Nothing changes even if I pull down to refresh the albums and each individual photo. 

I did look into Google photo, but decided against it due to the limited storage for full resolution photos.

**Comment by EddyLB** [comment]
The same issue happened recently to a user.
That was fixed by replacing the invalid SSL certificate of his server.
